In [1]:
import tensorflow as tf
import numpy as np

In [2]:
a = tf.Variable([1,2,3,4])
a.numpy()

array([1, 2, 3, 4], dtype=int32)

In [3]:
st1 = tf.SparseTensor(indices = [[0,3],[2,4]], values = [10,20], dense_shape= [3,10])
st1
#  [0, 0, 0, 10, 0, 0, 0, 0, 0, 0],
#  [0, 0, 0,  0, 0, 0, 0, 0, 0, 0],
#  [0, 0, 0,  0,20, 0, 0, 0, 0, 0]

SparseTensor(indices=tf.Tensor(
[[0 3]
 [2 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([10 20], shape=(2,), dtype=int32), dense_shape=tf.Tensor([ 3 10], shape=(2,), dtype=int64))

In [4]:
np_array = np.array([[1,0,0,0], [0,0,0,0], [0,0,2,0], [0,0,0,4]])  
np_array

array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 4]])

In [5]:
st2 = tf.sparse.from_dense(np_array)
st2

SparseTensor(indices=tf.Tensor(
[[0 0]
 [2 2]
 [3 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1 2 4], shape=(3,), dtype=int64), dense_shape=tf.Tensor([4 4], shape=(2,), dtype=int64))

In [6]:
st2.values.numpy()

array([1, 2, 4])

In [7]:
st2.values.numpy().tolist()

[1, 2, 4]

In [8]:
st2.indices.numpy().tolist()

[[0, 0], [2, 2], [3, 3]]

In [9]:
st2.dense_shape.numpy().tolist()

[4, 4]

In [10]:
den = tf.sparse.to_dense(st2)

In [11]:
den.numpy()

array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 4]])

In [12]:
st_add = tf.sparse.add(st2, st2)
st_add

SparseTensor(indices=tf.Tensor(
[[0 0]
 [2 2]
 [3 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([2 4 8], shape=(3,), dtype=int64), dense_shape=tf.Tensor([4 4], shape=(2,), dtype=int64))

In [13]:
ones_2d = tf.ones((2,2),tf.float32)
ones_2d

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [14]:
ones_2d = tf.ones((2,2,4),tf.float32)
ones_2d

<tf.Tensor: shape=(2, 2, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [15]:
ones_2d.shape

TensorShape([2, 2, 4])

In [16]:
cont_2dt = tf.constant([[1,2,3,],[4,5,6]])
cont_2dt

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [17]:
ones_2d = tf.ones_like(cont_2dt)
ones_2d

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [18]:
var_2d = tf.Variable([[1,2,3],[4,5,6]])
var_2d

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [19]:
ones_from_var2d = tf.ones_like(var_2d)
ones_from_var2d

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [20]:
def ones_variable(shape, dtype, initializer):
    return tf.Variable(initializer(shape=shape, dtype=dtype))  

In [21]:
ones_variable((2,2), tf.float32, tf.ones_initializer())

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [22]:
ones_variable((2,2,4), tf.float32, tf.ones_initializer())

<tf.Variable 'Variable:0' shape=(2, 2, 4) dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [23]:
zeros_2d = tf.zeros((2,2,4),tf.float32)
zeros_2d

<tf.Tensor: shape=(2, 2, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [24]:
zeros_2d.numpy()

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)

In [25]:
zeros_2d.numpy().tolist()

[[[0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0]],
 [[0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0]]]

In [26]:
cont_2dt = tf.constant([[1,2,3,],[4,5,6]])
cont_2dt

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [27]:
zeros_2d = tf.zeros_like(cont_2dt)
zeros_2d

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [28]:
bool_2d = tf.zeros_like(cont_2dt,dtype =tf.bool)
bool_2d

<tf.Tensor: shape=(2, 3), dtype=bool, numpy=
array([[False, False, False],
       [False, False, False]])>

In [29]:
def zeros_variable(shape, dtype, initializer):
    return tf.Variable(initializer(shape=shape, dtype=dtype))  

In [30]:
zeros_variable((2,2), tf.float32, tf.zeros_initializer())

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [31]:
a = 10
b = 20

In [32]:
tf.add(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [33]:
t1 = [1,2,3,4] 
t2 = [5,6,7,8]  
tf.add(t1, t2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 6,  8, 10, 12], dtype=int32)>

In [36]:
t3 = (6,7,8,9)  
tf.add(t1, t3)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 7,  9, 11, 13], dtype=int32)>

In [37]:
tf.add(t1, a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([11, 12, 13, 14], dtype=int32)>

In [41]:
npa1 = np.array([1,2,3,4,5])
npa2 = np.array([1,2,3,4,5])
tf.add(npa1,npa2)


<tf.Tensor: shape=(5,), dtype=int64, numpy=array([ 2,  4,  6,  8, 10])>

In [44]:
npa1 = np.array([1,2,3,4,5])
npa2 = np.array([2])
tf.add(npa1, npa2)
#only wprks in np

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([3, 4, 5, 6, 7])>

In [45]:
#same in constant and variable

In [46]:
x = np.ones(6).reshape(1,2,1,3)
x

array([[[[1., 1., 1.]],

        [[1., 1., 1.]]]])

In [50]:
y = np.ones(6).reshape(2,1,3,1) #2,2,3,3
y

array([[[[1.],
         [1.],
         [1.]]],


       [[[1.],
         [1.],
         [1.]]]])

In [51]:
tf.add(x,y)

<tf.Tensor: shape=(2, 2, 3, 3), dtype=float64, numpy=
array([[[[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]]],


       [[[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]]]])>

In [52]:
tf.subtract(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=-10>

In [53]:
#subtract same as add

In [54]:
tf.multiply(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=200>

In [55]:
#same as add

In [57]:
t1 = [1,2,3,4] 
t2 = [5,6,7,8]  

In [58]:
tf.multiply(t1,t2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 5, 12, 21, 32], dtype=int32)>

In [61]:
t1 = [1,2,3,4] 
t3 = [5,6,8]  

In [62]:
tf.multiply(x,y)

<tf.Tensor: shape=(2, 2, 3, 3), dtype=float64, numpy=
array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]])>

In [65]:
tf.divide(a,b)

<tf.Tensor: shape=(), dtype=float64, numpy=0.5>

In [66]:
#doesnt work with touple and list, but 

In [68]:
npa1 = np.array([1,2,3,4,5])
npa2 = np.array([1,2,3,4,5]) 
tf.divide(npa1, npa2)  

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([1., 1., 1., 1., 1.])>

In [69]:
tf.divide(npa1, a)  


<tf.Tensor: shape=(5,), dtype=float64, numpy=array([0.1, 0.2, 0.3, 0.4, 0.5])>

In [71]:
tf.sqrt(9.0)

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [73]:
l1 = [4.0,9.0,16.0] 
tf.sqrt(l1)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>

In [74]:
npa1 = np.array([4,9,16], dtype = np.float64)  
tf.sqrt(npa1)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 3., 4.])>

In [75]:
tf.sqrt(tf.convert_to_tensor(4, dtype='float'))

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [76]:
tf.pow(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=1661992960>

In [77]:
tf.pow(t1,t2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([    1,    64,  2187, 65536], dtype=int32)>

In [78]:
tf.maximum(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=20>

In [79]:
tf.maximum(l1,a)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([10., 10., 16.], dtype=float32)>

In [81]:
t1 = [1,2,3,40] 
t2 = [5,6,7,8]  
tf.maximum(t1,t2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 5,  6,  7, 40], dtype=int32)>

In [86]:
tf.minimum(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=10>