In [62]:
import tensorflow as tf
import numpy as np

In [3]:
tf.__version__

'2.21.0'

In [4]:
tf.constant(12)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [5]:
tf.constant(12.3)

<tf.Tensor: shape=(), dtype=float32, numpy=12.300000190734863>

In [6]:
tf.constant(True)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [7]:
tf.constant("ai")

<tf.Tensor: shape=(), dtype=string, numpy=b'ai'>

In [8]:
tf.constant([1,2,3,4])

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [9]:
tf.constant([[1,2],[3,4]])

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [10]:
tf.constant([[1,2],[3,4],[5,6]])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [11]:
tf.constant([1,2,3,4], shape =(2,2), dtype="float32")


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [12]:
arr = tf.constant(np.array([1,2,3,4]))
arr

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [13]:
a = tf.Variable([1,2,3,4])
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [14]:
a.name

'Variable:0'

In [15]:
a.shape

TensorShape([4])

In [16]:
a.dtype

tf.int32

In [17]:
a.numpy()

array([1, 2, 3, 4], dtype=int32)

In [18]:
b = tf.reshape(a,(2,2))
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [19]:
tf.Variable(3 +4j)

<tf.Variable 'Variable:0' shape=() dtype=complex128, numpy=(3+4j)>

In [20]:
#same as comstant

In [21]:
tf.argmax(a) #index of highest value

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [22]:
tf.argmax(b)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1])>

In [23]:
tf.argmax(b).numpy()

array([1, 1])

In [63]:
tf.argmax(b).numpy()

AttributeError: 'SymbolicTensor' object has no attribute 'numpy'

In [24]:
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [25]:
tf.convert_to_tensor(a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [26]:
a.assign([4,6,2,8])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([4, 6, 2, 8], dtype=int32)>

In [27]:
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([4, 6, 2, 8], dtype=int32)>

In [28]:
tf.compat.v1.disable_eager_execution()

In [29]:
a1 = tf.placeholder(dtype=tf.float32, shape = (400,400))
a1

AttributeError: module 'tensorflow' has no attribute 'placeholder'

In [31]:
a = tf.compat.v1.placeholder(dtype=tf.float32, shape = (400,400))
a

<tf.Tensor 'Placeholder:0' shape=(400, 400) dtype=float32>

In [32]:
b = tf.compat.v1.placeholder(dtype=tf.float32, shape = (400,400))
b

<tf.Tensor 'Placeholder_1:0' shape=(400, 400) dtype=float32>

In [33]:
c = tf.add(a,b)

In [34]:
ones_array = np.ones((400,400), np.float32) 
ones_array

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], shape=(400, 400), dtype=float32)

In [35]:
with tf.compat.v1.Session() as sess: 
    d = sess.run(c, feed_dict={a:ones_array, b:ones_array})

In [36]:
d

array([[2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       ...,
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.]], shape=(400, 400), dtype=float32)

In [37]:
x = tf.compat.v1.placeholder(tf.float32)
y = tf.compat.v1.placeholder(tf.float32)

z = x + y

with tf.compat.v1.Session() as sess:
    result = sess.run(z, feed_dict={x: 2, y: 3})
    print(result)

print(result)

5.0
5.0


In [38]:
type(d)

numpy.ndarray

In [39]:
a.name

'Placeholder:0'